name: Build and Deploy App
on:
  push:
    branches:
      - score-test
env:
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, production]
    env:
      CONTEXT: ${{ matrix.environment }}
      
    steps:
      - name: Checkout App Code
        uses: actions/checkout@v3

      - name: Install Score CLI
        uses: score-spec/setup-score@v2
        with:
          file: score-k8s
          version: '0.6.1'
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Initialize Score Yaml
        run: |
          score-k8s --version
          score-k8s init

      - name: Clone Platform Repository
        run: |
            git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/platform-resources.git
      - name: Deploy using score-k8s to ${{ matrix.environment }}
        run: |
          score-k8s apply \
            --file score.yaml \
            --context ${{ matrix.environment }} \
            --resource-mapping platform-resources/resource-mapping-multi-env.yaml \
            --modules-path platform-resources/

